### ISSUE TITLE
tag <description> uses currently-selected shopfront language instead of admin-selected feed language

### ISSUE THREAD

**Issue by torvista** [lat9/gpsf#20]
from here: https://github.com/lat9/gpsf/blob/e73e3974a3989eb88e59051343a1dc78a6533d92/includes/classes/gpsfFeedGenerator.php#L452

**Comment by torvista** [comment]
Since I pull in boilerplate text constants into the product descriptions, these were also not in sync with the selected feed language.
After a **lot** of trial and error, the only thing that works (for me) is setting $_GET['language'] = the language code, before application_top is called.
If the language code was passed from admin to controller (instead of the id), this would be easier to use (I used a switch for now).

**Comment by lat9** [comment]
I'll be dealing with that via some simplification for the feed-generation language handling, essentially letting the base Zen Cart storefront processing deal with it.

Instead of passing `$_GET['language_id']` from the admin tool to the storefront feed-generator, changing that to pass `$_GET['language']` (the language code) should "do the trick".

**Comment by lat9** [comment]
Noting, too, that this correction will remove the `GPSF_LANGUAGE` configuration setting, in deference to a store's `DEFAULT_LANGUAGE`.

**Comment by lat9** [comment]
> works for me.

Was that in response to the missing language-suffix?

**Comment by torvista** [comment]
yes.
